config/routes.rb
Rails.application.routes.draw do
  resources :calendards
  resources :calendars
  resources :calendarios
  get 'generate_fixture/index'
  get 'hello_world', to: 'hello_world#index'
  # get 'main', to: 'main#index'
  root :to => 'main#index'
  resources :teams
  resources :matches
  resources :positions
  resources :fixtures
  resources :tournaments
  resources :generate_fixture
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/calendard.rb
class Calendard < ApplicationRecord
end

app/models/calendario.rb
class Calendario < ApplicationRecord
end

app/models/fixture.rb
    class Fixture < ApplicationRecord
        attr_reader :teams, :home_rounds, :away_rounds
      
        def initialize(teams)
          @teams = teams
          @home_rounds = []
          @away_rounds = []
        end
      
        def rounds
          number_of_rounds.times do
            matches_home = []
            matches_away = []
      
            number_of_matches.times do |index|
              team_1 = teams[index]
              team_2 = teams[number_of_rounds - index]
      
              matches_home << [team_1, team_2]
              matches_away << [team_2, team_1]
            end
      
            home_rounds << matches_home
            away_rounds << matches_away
      
            rotate_teams!
          end
      
          return home_rounds + away_rounds
        end
      
        private
      
        def rotate_teams!
          last = teams.pop
          teams.insert(1, last)
        end
      
        def number_of_rounds
          @rounds ||= (teams.length - 2) + 1
        end
      
        def number_of_matches
          @matches ||= (teams.length / 2)
        end
      end
      
      def print_rounds(rounds)
        i = 1
        rounds.each do |round|
          puts "Round: #{i}"
          round.each do |match|
            puts "Match: #{match[0]} - #{match[1]}"
          end
          i += 1
        end
    end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/test_model.rb
class TestModel < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout "main"
  
  def index
    @main_props = { name: "Fernando" }
    #render : template => 'index'
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: %i[ show edit update destroy ]

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1 or /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:id_tournament, :id_team, :points, :played, :won, :tied, :lost, :goals_converted, :goals_received, :goals_diference)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendards_helper.rb
module CalendardsHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_tournament %>
    <%= form.number_field :id_tournament %>
  </div>

  <div class="field">
    <%= form.label :id_team %>
    <%= form.number_field :id_team %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="field">
    <%= form.label :played %>
    <%= form.number_field :played %>
  </div>

  <div class="field">
    <%= form.label :won %>
    <%= form.number_field :won %>
  </div>

  <div class="field">
    <%= form.label :tied %>
    <%= form.number_field :tied %>
  </div>

  <div class="field">
    <%= form.label :lost %>
    <%= form.number_field :lost %>
  </div>

  <div class="field">
    <%= form.label :goals_converted %>
    <%= form.number_field :goals_converted %>
  </div>

  <div class="field">
    <%= form.label :goals_received %>
    <%= form.number_field :goals_received %>
  </div>

  <div class="field">
    <%= form.label :goals_diference %>
    <%= form.number_field :goals_diference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Id tournament</th>
      <th>Id team</th>
      <th>Points</th>
      <th>Played</th>
      <th>Won</th>
      <th>Tied</th>
      <th>Lost</th>
      <th>Goals converted</th>
      <th>Goals received</th>
      <th>Goals diference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.id_tournament %></td>
        <td><%= position.id_team %></td>
        <td><%= position.points %></td>
        <td><%= position.played %></td>
        <td><%= position.won %></td>
        <td><%= position.tied %></td>
        <td><%= position.lost %></td>
        <td><%= position.goals_converted %></td>
        <td><%= position.goals_received %></td>
        <td><%= position.goals_diference %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id tournament:</strong>
  <%= @position.id_tournament %>
</p>

<p>
  <strong>Id team:</strong>
  <%= @position.id_team %>
</p>

<p>
  <strong>Points:</strong>
  <%= @position.points %>
</p>

<p>
  <strong>Played:</strong>
  <%= @position.played %>
</p>

<p>
  <strong>Won:</strong>
  <%= @position.won %>
</p>

<p>
  <strong>Tied:</strong>
  <%= @position.tied %>
</p>

<p>
  <strong>Lost:</strong>
  <%= @position.lost %>
</p>

<p>
  <strong>Goals converted:</strong>
  <%= @position.goals_converted %>
</p>

<p>
  <strong>Goals received:</strong>
  <%= @position.goals_received %>
</p>

<p>
  <strong>Goals diference:</strong>
  <%= @position.goals_diference %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>