config/routes.rb
Rails.application.routes.draw do
  resources :calendards
  resources :calendars
  resources :calendarios
  get 'generate_fixture/index'
  get 'hello_world', to: 'hello_world#index'
  # get 'main', to: 'main#index'
  root :to => 'main#index'
  resources :teams
  resources :matches
  resources :positions
  resources :fixtures
  resources :tournaments
  resources :generate_fixture
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/calendard.rb
class Calendard < ApplicationRecord
end

app/models/calendario.rb
class Calendario < ApplicationRecord
end

app/models/fixture.rb
    class Fixture < ApplicationRecord
        attr_reader :teams, :home_rounds, :away_rounds
      
        def initialize(teams)
          @teams = teams
          @home_rounds = []
          @away_rounds = []
        end
      
        def rounds
          number_of_rounds.times do
            matches_home = []
            matches_away = []
      
            number_of_matches.times do |index|
              team_1 = teams[index]
              team_2 = teams[number_of_rounds - index]
      
              matches_home << [team_1, team_2]
              matches_away << [team_2, team_1]
            end
      
            home_rounds << matches_home
            away_rounds << matches_away
      
            rotate_teams!
          end
      
          return home_rounds + away_rounds
        end
      
        private
      
        def rotate_teams!
          last = teams.pop
          teams.insert(1, last)
        end
      
        def number_of_rounds
          @rounds ||= (teams.length - 2) + 1
        end
      
        def number_of_matches
          @matches ||= (teams.length / 2)
        end
      end
      
      def print_rounds(rounds)
        i = 1
        rounds.each do |round|
          puts "Round: #{i}"
          round.each do |match|
            puts "Match: #{match[0]} - #{match[1]}"
          end
          i += 1
        end
    end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/test_model.rb
class TestModel < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  before_action :set_fixture, only: %i[ show edit update destroy ]

  # GET /fixtures or /fixtures.json
  def index
    @fixtures = Fixture.all
  end

  # GET /fixtures/1 or /fixtures/1.json
  def show
  end

  # GET /fixtures/new
  def new
    @fixture = Fixture.new
  end

  # GET /fixtures/1/edit
  def edit
  end

  # POST /fixtures or /fixtures.json
  def create
    @fixture = Fixture.new(fixture_params)

    respond_to do |format|
      if @fixture.save
        format.html { redirect_to @fixture, notice: "Fixture was successfully created." }
        format.json { render :show, status: :created, location: @fixture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixtures/1 or /fixtures/1.json
  def update
    respond_to do |format|
      if @fixture.update(fixture_params)
        format.html { redirect_to @fixture, notice: "Fixture was successfully updated." }
        format.json { render :show, status: :ok, location: @fixture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1 or /fixtures/1.json
  def destroy
    @fixture.destroy
    respond_to do |format|
      format.html { redirect_to fixtures_url, notice: "Fixture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fixture
      @fixture = Fixture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fixture_params
      params.require(:fixture).permit(:id_tournament, :id_match, :round, :local, :visitor, :l_goals, :v_goals)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout "main"
  
  def index
    @main_props = { name: "Fernando" }
    #render : template => 'index'
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendards_helper.rb
module CalendardsHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/fixtures/_form.html.erb
<%= form_with(model: fixture) do |form| %>
  <% if fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
        <% fixture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_tournament %>
    <%= form.number_field :id_tournament %>
  </div>

  <div class="field">
    <%= form.label :id_match %>
    <%= form.number_field :id_match %>
  </div>

  <div class="field">
    <%= form.label :round %>
    <%= form.number_field :round %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.number_field :local %>
  </div>

  <div class="field">
    <%= form.label :visitor %>
    <%= form.number_field :visitor %>
  </div>

  <div class="field">
    <%= form.label :l_goals %>
    <%= form.number_field :l_goals %>
  </div>

  <div class="field">
    <%= form.label :v_goals %>
    <%= form.number_field :v_goals %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing Fixture</h1>

<%= render 'form', fixture: @fixture %>

<%= link_to 'Show', @fixture %> |
<%= link_to 'Back', fixtures_path %>

app/views/fixtures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fixtures</h1>

<table>
  <thead>
    <tr>
      <th>Id tournament</th>
      <th>Id match</th>
      <th>Round</th>
      <th>Local</th>
      <th>Visitor</th>
      <th>L goals</th>
      <th>V goals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fixtures.each do |fixture| %>
      <tr>
        <td><%= fixture.id_tournament %></td>
        <td><%= fixture.id_match %></td>
        <td><%= fixture.round %></td>
        <td><%= fixture.local %></td>
        <td><%= fixture.visitor %></td>
        <td><%= fixture.l_goals %></td>
        <td><%= fixture.v_goals %></td>
        <td><%= link_to 'Show', fixture %></td>
        <td><%= link_to 'Edit', edit_fixture_path(fixture) %></td>
        <td><%= link_to 'Destroy', fixture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fixture', new_fixture_path %>

app/views/fixtures/new.html.erb
<h1>New Fixture</h1>

<%= render 'form', fixture: @fixture %>

<%= link_to 'Back', fixtures_path %>

app/views/fixtures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id tournament:</strong>
  <%= @fixture.id_tournament %>
</p>

<p>
  <strong>Id match:</strong>
  <%= @fixture.id_match %>
</p>

<p>
  <strong>Round:</strong>
  <%= @fixture.round %>
</p>

<p>
  <strong>Local:</strong>
  <%= @fixture.local %>
</p>

<p>
  <strong>Visitor:</strong>
  <%= @fixture.visitor %>
</p>

<p>
  <strong>L goals:</strong>
  <%= @fixture.l_goals %>
</p>

<p>
  <strong>V goals:</strong>
  <%= @fixture.v_goals %>
</p>

<%= link_to 'Edit', edit_fixture_path(@fixture) %> |
<%= link_to 'Back', fixtures_path %>