config/routes.rb
Rails.application.routes.draw do
  resources :calendards
  resources :calendars
  resources :calendarios
  get 'generate_fixture/index'
  get 'hello_world', to: 'hello_world#index'
  # get 'main', to: 'main#index'
  root :to => 'main#index'
  resources :teams
  resources :matches
  resources :positions
  resources :fixtures
  resources :tournaments
  resources :generate_fixture
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/calendard.rb
class Calendard < ApplicationRecord
end

app/models/calendario.rb
class Calendario < ApplicationRecord
end

app/models/fixture.rb
    class Fixture < ApplicationRecord
        attr_reader :teams, :home_rounds, :away_rounds
      
        def initialize(teams)
          @teams = teams
          @home_rounds = []
          @away_rounds = []
        end
      
        def rounds
          number_of_rounds.times do
            matches_home = []
            matches_away = []
      
            number_of_matches.times do |index|
              team_1 = teams[index]
              team_2 = teams[number_of_rounds - index]
      
              matches_home << [team_1, team_2]
              matches_away << [team_2, team_1]
            end
      
            home_rounds << matches_home
            away_rounds << matches_away
      
            rotate_teams!
          end
      
          return home_rounds + away_rounds
        end
      
        private
      
        def rotate_teams!
          last = teams.pop
          teams.insert(1, last)
        end
      
        def number_of_rounds
          @rounds ||= (teams.length - 2) + 1
        end
      
        def number_of_matches
          @matches ||= (teams.length / 2)
        end
      end
      
      def print_rounds(rounds)
        i = 1
        rounds.each do |round|
          puts "Round: #{i}"
          round.each do |match|
            puts "Match: #{match[0]} - #{match[1]}"
          end
          i += 1
        end
    end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/test_model.rb
class TestModel < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout "main"
  
  def index
    @main_props = { name: "Fernando" }
    #render : template => 'index'
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:id_tournament, :date)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendards_helper.rb
module CalendardsHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_tournament %>
    <%= form.number_field :id_tournament %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Id tournament</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.id_tournament %></td>
        <td><%= match.date %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id tournament:</strong>
  <%= @match.id_tournament %>
</p>

<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>